### ISSUE TITLE
[Request] Disable plugin on a per-browser basis

### ISSUE THREAD

**Issue by cp2004** [jneilliii/OctoPrint-WideScreen#12]
It would be *nice* if I could disable this plugin on one browser. My setup is a 7inch touchscreen by the printer, which looks OK with the default web interface, since it is full screen. While I really like this plugin for my larger screens, I don't want it on all the time.

Is there a simple way you could make this an option, stored via a cookie or something? If it is too complex, don't worry about it, I can live with it 😃

**Comment by jneilliii** [comment]
Maybe detecting screen resolution would work as an automatic way of enabling/disabling without user intervention?

**Comment by cp2004** [comment]
I was just scrolling through open issues I had, seems this one got forgotten - my PR was merged 😄.
