### ISSUE TITLE
No draggable items

### ISSUE THREAD

**Issue by Hufnagels** [jneilliii/OctoPrint-WideScreen#13]
Hi, first off all, thx for plugin.
I installed and empty div are in source. There isn't a right sidebar created.
Attached link is an image of it [https://ibb.co/CKz5LZk](url). (system params are on the image.

Can u help to resolv this issue?

Thx

**Comment by KenLucke** [comment]
Are you trying to drag on the main screen, or in the plugin's settings page?

**Comment by Hufnagels** [comment]
on the settings page. the draggable containers are empty

**Comment by jneilliii** [comment]
@Hufnagels can you open your browser's developer console and share a screenshot of any possible errors that might be displayed during initial page load or when you open the settings for OctoPrint?
