### ISSUE TITLE
widescreen makes webcam stream mushy

### ISSUE THREAD

**Issue by Ajimaru** [jneilliii/OctoPrint-WideScreen#18]
The widescreen plugin makes the webcam stream integrated in the dashboard tab mushy.

With acitvated widescreen plugin:
![grafik](https://user-images.githubusercontent.com/38381946/102482136-0d0fa080-4063-11eb-934a-92e9e59614be.png)

Without activated widescreen plugin:
![grafik](https://user-images.githubusercontent.com/38381946/102482448-7b546300-4063-11eb-9c51-514782b20605.png)

Is there a possibility to keep the original aspect ratio of the webcam stream?

**Comment by jneilliii** [comment]
So I'm assuming this would have to be handled by the dashboard plugin, not this one as it's stretching the image to the available size. However, I'm going to be retiring this plugin soon as the new UI Customizer plugin is far more advanced and a better solution than this one. You may want to try that one out to see if it has the same issue or not.
