### ISSUE TITLE
How to get rid of right panel?

### ISSUE THREAD

**Issue by Mosher23** [jneilliii/OctoPrint-WideScreen#2]
How can i get rid of right panel?
I don't want to use it, but it is reserving place on screen!
<img width="1829" alt="Screenshot 2020-03-22 at 12 06 38" src="https://user-images.githubusercontent.com/8256425/77247895-99f10f00-6c35-11ea-9bca-f7dfa05a3bb7.png">

**Comment by jneilliii** [comment]
Disable the plugin and it will go back to the default.

**Comment by jneilliii** [comment]
If you don't want to put any of the panels into the right sidebar that this plugin adds you may want to look into the community forum post linked below for modifying the UI just using Themify's advanced settings and disabled this plugin.

https://community.octoprint.org/t/pimp-my-web-interface/3349
