### ISSUE TITLE
[Idea] Terminal on left/right side

### ISSUE THREAD

**Issue by AndiP1234** [jneilliii/OctoPrint-WideScreen#21]
Hi,
you are doing really great work on the plugins!

I just got the idea to slide the terminal (or one of the other middle tabs) on one of the two sides. Maybe you think that's just as cool as I do ;) 
Unfortunately my skills are not enough to implement this :(

Best regards
Andi

**Comment by jneilliii** [comment]
There's some underlying complexity with moving things between tabs and sidebars that will break tab functionality. I do however have the Consolidated Tabs plugin that allows you to combine tabs so you can have the ones you use the most on a single pane. I actually consolidate all the tabs in my OctoPrint and it condenses down to a single page interface.

![image](https://user-images.githubusercontent.com/5249455/111888343-0d953b80-89b2-11eb-9c06-fbf4dd21a995.png)
