### ISSUE TITLE
Super Ultra Wide

### ISSUE THREAD

**Issue by arne182** [jneilliii/OctoPrint-WideScreen#22]
![image](https://user-images.githubusercontent.com/844102/120903356-09d69400-c646-11eb-84c8-c2a4784f532d.png)

It would be nice if the files menu would go all the way to the bottom of the page.

The Camera preview at this size also  causes the controls to be out of the page and you have to scroll down to see them.

**Comment by jneilliii** [comment]
I'd recommend using UI Customizer instead of this plugin for more advanced customization. I'm kind of not really looking to develop this plugin any more since that one is more customizable.
