### ISSUE TITLE
Widescreen G-Code Viewer size

### ISSUE THREAD

**Issue by ILogEverything** [jneilliii/OctoPrint-WideScreen#23]
As displayed here, G-Code Viewer doesn't works well

![image](https://user-images.githubusercontent.com/116915198/207023506-1b458762-54c3-4cb1-b431-37c8bc3d75fe.png)

**Comment by jneilliii** [comment]
Yeah, I never really was able to work that out. Not sure if UI Customizer (widescreen and theme support combined) handles this any better or not, but you might want to check that out as a possible replacement.

**Comment by jneilliii** [comment]
duplicate #3 and #10.
