### ISSUE TITLE
Forming right side column issues.  

### ISSUE THREAD

**Issue by Ecks32** [jneilliii/OctoPrint-WideScreen#24]
Hello. first let me say that I have been able to arrange panels as needed but had problems doing so.  I  thought I would report the issues but I don't need help at this time.

1. None of the panels can be dragged when using Firefox.  I was able to drag them using Vivaldi but still had issues.
2. Using Vivaldi, panels would snap back to the left after being dragged over.  
3. Eventually I was able to get "sidebar_plugin_firmware_check_warning" to stay on the right panel.
4. I was then able to get "sidebar_plugin_firmware_check_info" to drag over and stay but only if placed above the previous panel.
5. Only then could I get other panels to stay on the right but only if they were dragged between the first two.
6. After getting all the panels I needed on the right I was able to drag them up and down to arrange them. 

I looked at the developer console in Firefox, as I read in another post, but did not see any errors.  I likely didn't know what to look for so there could have been errors. 

Hope this information is helpful.  Thanks for the great plugin.

**Comment by jneilliii** [comment]
I'd recommend UI Customizer over this plugin now a days. It's far more advanced, with greater control and flexibility of the column layouts.
