### ISSUE TITLE
GCode Layer View Doesn't Resize

### ISSUE THREAD

**Issue by RobertCowanDIY** [jneilliii/OctoPrint-WideScreen#3]
The window for the layer views in the 'GCode Viewer' tab doesn't resize with the window.  It persists as the same size and won't dynamically resize with the other elements, leaving a gap on the right-hand side.

**Comment by jneilliii** [comment]
That is actually by design because resizing the gcode tab causes other non-fixable issues without changes to the core OctoPrint.
