### ISSUE TITLE
When Files panel is on right side bar, settings menu overflows browser window

### ISSUE THREAD

**Issue by Vic-Y** [jneilliii/OctoPrint-WideScreen#4]
Thanks for developing this plugin.

When the Files panel is in the right side bar, the settings menu overflows the browser window.

![image](https://user-images.githubusercontent.com/62916399/84098427-792e8f00-a9c4-11ea-8722-8c7c16bb00de.png)

**Comment by jneilliii** [comment]
Thanks for reporting, I'll take a look into this.

**Comment by jneilliii** [comment]
Just pushed above commit, to be released in version 0.1.2.

**Comment by Vic-Y** [comment]
Great! Thanks.
