### ISSUE TITLE
Layout issue when used with Dashboard plugin in fullscreen

### ISSUE THREAD

**Issue by Nebby** [jneilliii/OctoPrint-WideScreen#5]
When the [Dashboard plugin](https://github.com/StefanCohen/OctoPrint-Dashboard) is in fullscreen mode, right side bar is overlaid on top of the dashboard view.

**Comment by jneilliii** [comment]
I'm looking into this now. I've recently had to do other tweaks to deal with some of Dashboard plugins css rules.

**Comment by jneilliii** [comment]
Opened issue [here](https://github.com/StefanCohen/OctoPrint-Dashboard/issues/182).
