### ISSUE TITLE
The OctoPrint-WideScreen plugin breaks the OctoPrint-TouchUI plugin

### ISSUE THREAD

**Issue by compmas2** [jneilliii/OctoPrint-WideScreen#6]
When the OctoPrint-Wide-Screen plugin is enabled and configured for parts of the screen to be on the right side, they no longer appear in the OctoPrint-TouchUI view on mobile devices or Raspberry Pi touchscreens.

I really like this plugin for using with a computer, but I can't use it since it is breaking my other views.  Is there a way to detect if the OctoPrint-TouchUI plugin is active (mobile display) and disable the WideScreen functionality?  That would solve the issue.

Here is a link to the OctoPrint-TouchUI Homepage (https://github.com/BillyBlaze/OctoPrint-TouchUI)

**Comment by jneilliii** [comment]
Just released version 0.1.3 that resolves this issue.
