### ISSUE TITLE
Uninstall leaves screen the same

### ISSUE THREAD

**Issue by 5ft24dave** [jneilliii/OctoPrint-WideScreen#8]
Installed plugin, moved items around, didn't really like the way it looked, uninstalled plugin, Screen stayed the same.  rebooted pi, cleared browser cache, reloaded, screen still stays in wide screen layout from before the uninstall.

**Comment by jneilliii** [comment]
The plugin makes no changes to the core octoprint interface, so uninstalling and forcing a refresh of the browser cache should be plenty to make the UI go back to default.

**Comment by 5ft24dave** [comment]
This is after doing an uninstall and data removal of the plugin, cleared
all browser data, cookies etc, same screen.  Went to another computer at
work that I have never logged into my Octoprint with, rebooted the
octoprint server via ssh first, then logged into Octoprint web interface.
Still in wide format.

**Comment by jneilliii** [comment]
It almost sounds like it didn't uninstall cleanly. If you ssh to your pi and run the command `~/oprint/bin/pip freeze` do you see `OctoPrint-WideScreen` listed?

**Comment by jneilliii** [comment]
I just tested this and it went back to default non-widescreen format upon uninstall and cleaning data. So not sure what your issue might be here. Are you using any other UI based plugins like Themeify that might be causing this?

**Comment by 5ft24dave** [comment]
Nope:

OctoPrint-RequestSpinner==0.2.0
OctoPrint-Resource-Monitor==0.2.3
OctoPrint-SimpleEmergencyStop==1.0.1
OctoPrint-Stats==2.0.2
OctoPrint-SystemCommandEditor==0.3.4
OctoPrint-TabOrder==0.5.8
OctoPrint-Tempsgraph==0.3.6
OctoPrint-WebcamTab==0.1.2
pandas==0.24.2
pathtools==0.1.2
peewee==3.13.3
pigpio==1.35

**Comment by 5ft24dave** [comment]
I do have Themeify... let me remove that and see what happens

**Comment by 5ft24dave** [comment]
re-installed wide screen, removed and cleared data for themeify, reloaded
server, removed wide-screen and all data, reloaded octoprint, while it was
reloading I cleared all cookies/cache etc in the browser, came back up and
it's the same just without the dark theme on it...

**Comment by 5ft24dave** [comment]
Just uninstalled themeify and the wide-screen, and restored a backup from
Feb.  still coming up in the widescreen mode...  Looks like I need to copy
my backup files off to another drive and blow it away, reinstall and
restore the good backup...
Up unitl this plugin, I had the system running exactly the way I wanted
it...
Starting over is fucked up[

**Comment by jneilliii** [comment]
I'm baffled why this happened and sorry it's doing this, but if I can't reproduce the problem I can't figure out how to fix it. You're not using some form of a proxy caching server or anything are you?

**Comment by 5ft24dave** [comment]
nope, Just the octopi image.  changed ports in haproxy and did a port
forward on my router for external access is all.

**Comment by jneilliii** [comment]
Instead of going through the whole re-flash scenario you can do these commands via SSH on your pi to start fresh. Download the backup prior and use that to restore after this process.
```
sudo service octoprint stop
mv ~/oprint ~/oprint.bak
virtualenv --python=/usr/bin/python oprint
source ~/oprint/bin/activate
pip install OctoPrint
deactivate
sudo service octoprint start
```

**Comment by 5ft24dave** [comment]
Ah!
I can do that remotely here from work!
Thank you

**Comment by jneilliii** [comment]
That's why I was curious about the proxy cache question. If your work implements one of those that could potentially be the problem...

**Comment by 5ft24dave** [comment]
I use their external open network for my play stuff LOL

⁣Get BlueMail for Android ​
